# Dummy markdown test 

In [1]:
import numpy as np


random = np.random.rand(3,3)

print(random)

[[0.37847839 0.65600371 0.07422216]
 [0.80685558 0.76543729 0.80261601]
 [0.66493312 0.26663389 0.98243031]]
